### PR TITLE
Code snippets from ACE1pack paper

### PR DESCRIPTION
**Pull request by wcwitt**

### CODE REVIEW

**Comment by wcwitt** [comment]
Still need to add a few more and update non-working examples in paper.

**Comment by cortner** [comment]
I wonder whether this is really the place for this, or should it be a test inside of `ACE1pack.jl` so that it runs through CI?

**Comment by cortner** [comment]
@wcwitt  -- can I merge this?

**Comment by wcwitt** [comment]
Yes, let's merge.

**Pull request merged**
