### PR TITLE
Script for Refitting the Si-PRX ACE

### PR DESCRIPTION
**Pull request by cortner**
CC @casv2  -- this seems to work ok now, let me know if you have questions!

### CODE REVIEW

**Comment by cortner** [comment]
@casv2  -- I've added a second Si script that recomputes the weights. It seems to work. I don't have time to test now. Will try later but no promises.

**Comment by cortner** [comment]
@wcwitt  or @casv2  -- can you please push your final script to this branch. Cas, can you also add a link to the testing framework? Or post it here and I can add it.

**Comment by cortner** [comment]
btw, you both have push access, no need to use forks.

**Comment by cortner** [comment]
@JPDarby  -- can you please add you final Si script to this PR when you are done tomorrow?  If @jameskermode 's scripts can be added as well that would be great. Please also add a README documenting what these scripts contain and where the data is from. 

Thank you.

**Comment by jameskermode** [comment]
Yup, I'll push my fracture scripts here too.

**Comment by jameskermode** [comment]
I think this PR can this be closed in favour of #8

**Pull request closed without merging**
