### PR TITLE
Silicon Example

### PR DESCRIPTION
**Pull request by JPDarby**
Added fitting and fracture test scripts

### CODE REVIEW

**Comment by cortner** [comment]
Thank you, James. I'll review and merge this asap.

**Comment by cortner** [comment]
Thanks again. I've gone through, looks very useful, and we should consider adding your script to `ACEpotentials.jl` as a master script for people who want to fit via command line.

**Comment by cortner** [comment]
My only request before I merge: Would you be willing to change the name of the folder to something that links it to the PRX2018 paper? I used the years to indicate where the dataset is from rather than when the example was produced. E.g. I'd be fine with `Si_PRX18` or `Si2018` or something like that. 

We could use a different way to organize this if you have a good idea.

**Comment by cortner** [comment]
Hm, ... I'm getting very strange results, but let's assume this is a problem at my end ... 
```
(base) ortner@CosmicCrisp Silicon_2023 % j19 --project=. fit_model.jl
setting up basis...length(model.basis) = 5434
cutoff(model.basis.BB[1]) = 6.0
ERROR: pcre2 regexp got NOMATCH on atom line 0
fitting model...┌───────────────┬──────────┬───────┬────┬────┬────┐
│          Type │ #Configs │ #Envs │ #E │ #F │ #V │
├───────────────┼──────────┼───────┼────┼────┼────┤
│ isolated_atom │        1 │     1 │  1 │  3 │  0 │
├───────────────┼──────────┼───────┼────┼────┼────┤
│         total │        1 │     1 │  1 │  3 │  0 │
│       missing │        0 │     0 │  0 │  0 │  6 │
└───────────────┴──────────┴───────┴────┴────┴────┘
[ Info: Assembling linear problem.
[ Info:   - Creating feature matrix with size (4, 5434).
```

**Comment by cortner** [comment]
> ERROR: pcre2 regexp got NOMATCH on atom line 0

This is caused by 
```
train = JuLIP.read_extxyz(train_xyz)
```
I tried to download a fresh datafile, then read it again, no luck. @JPDarby what version of ExtXYZ do you have installed?

**Comment by cortner** [comment]
I now tried this also on my group server - there I get a segfault when trying to load the dataset.

**Comment by JPDarby** [comment]
Will look at this now!

**Comment by JPDarby** [comment]
If I instantiate from Project.toml only I get a segfault. If I instantiate from Project.toml **and** Manifest.toml it works. Will check versions now...

**Comment by JPDarby** [comment]
Summary of tests 

ExtXYZ version "0.1.12" it works and with version "0.1.13" it doesn't.
`add ExtXYZ@0.1.12` doesn't fix it...
extxyz_jll versions are different... "0.0.1+0" works but "0.0.3+0" doesn't...
also running `add extxyz_jll@0.0.1` does fix the issue`

**Comment by cortner** [comment]
Good catch, that hadn’t occured to me yet. Sounds like a version control issue at ExtXXZ?

**Comment by JPDarby** [comment]
Maybe but not 100% sure... making a minimum working example and will file an issue with ExtXYZ

**Comment by JPDarby** [comment]
https://github.com/libAtoms/ExtXYZ.jl/issues/44

**Comment by jameskermode** [comment]
I released a new version of ExtXYZ.jl so this should be OK now.

**Comment by JPDarby** [comment]
Thanks!

**Comment by jameskermode** [comment]
(Sorry for breaking it in the first place; didn't see this PR until now)

**Comment by cortner** [comment]
thank you both!!

**Pull request merged**
